platform :ios, '10.0'
use_frameworks!

target 'Actionable_Example' do
  pod 'Actionable', :path => '../'

  target 'Actionable_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
