platform :ios, '10.0'
use_frameworks!

target 'Actionable_Example' do
  pod 'Actionable', :path => '../'

  target 'Actionable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
