#!/bin/bash

SOURCERY_PATH=$PODS_ROOT/Sourcery/bin/sourcery
ACTIONABLE_PATH=$(dirname $0)
ACTIONABLE_SWIFT=$ACTIONABLE_PATH/Sources/Actionable.swift
ACTIONABLE_TEMPLATES=$ACTIONABLE_PATH/Resources/

while getopts "i:o:" opt; do
  case ${opt} in
    i )
      INPUT_DIR=$OPTARG
    ;;
    o )
      OUTPUT_FILE=$OPTARG
    ;;
    \? )
      echo "Usage: cmd [-i] [-o]"
      exit 1
    ;;
  esac
done

if [ -z $INPUT_DIR ]; then
  echo "Error: Actionable input directory not specified [-i]"
  exit 1
fi

if [ -z $OUTPUT_FILE ]; then
  echo "Error: Actionable output file not specified [-o]"
  exit 1
fi

$SOURCERY_PATH --sources $INPUT_DIR --sources $ACTIONABLE_SWIFT --templates $ACTIONABLE_TEMPLATES --output $OUTPUT_FILE
